export const AdminActionTypes = {
    SET_CURRENT_QNUM: 'SET_CURRENT_QNUM',
    SET_CURRENT_ADMIN: 'SET_CURRENT_ADMIN',
    SET_CURRENT_ADMIN_NAME: 'SET_CURRENT_ADMIN_NAME',
    SET_CURRENT_PASSWORD: 'SET_CURRENT_PASSWORD'
};